/**
 * CSP Nonce Context
 *
 * Provides the CSP nonce to client components that need it for inline scripts.
 * The nonce is generated by middleware and passed via headers.
 */

'use client'

import { createContext, useContext, type ReactNode } from 'react'

const NonceContext = createContext<string | undefined>(undefined)

interface NonceProviderProps {
  nonce?: string
  children: ReactNode
}

/**
 * Provider component for CSP nonce
 */
export function NonceProvider({ nonce, children }: NonceProviderProps) {
  return <NonceContext.Provider value={nonce}>{children}</NonceContext.Provider>
}

/**
 * Hook to access CSP nonce in client components
 *
 * @example
 * ```tsx
 * 'use client'
 * import { useNonce } from '@/lib/csp/nonce-context'
 *
 * function MyComponent() {
 *   const nonce = useNonce()
 *   return <script nonce={nonce}>console.log('safe')</script>
 * }
 * ```
 */
export function useNonce(): string | undefined {
  return useContext(NonceContext)
}
