-- ============================================
-- Migration: Create user_history table
-- Description: Historia aktywności użytkownika - wpisy z onboardingu, profilu, zjedzone posiłki
-- Author: Claude Code
-- Date: 2025-12-22
-- ============================================

-- 1. Typ ENUM dla rodzajów zdarzeń w historii
create type public.history_event_type_enum as enum (
  'profile_created',      -- Utworzenie profilu (onboarding)
  'profile_updated',      -- Aktualizacja profilu
  'meal_eaten'            -- Posiłek oznaczony jako zjedzony
);

-- 2. Tabela user_history w schemacie public
create table public.user_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type public.history_event_type_enum not null,
  event_date date not null default current_date,
  created_at timestamptz not null default now(),

  -- Dane profilu (dla profile_created i profile_updated)
  profile_snapshot jsonb,
  -- Struktura: {
  --   "weight_kg": 70,
  --   "height_cm": 165,
  --   "age": 30,
  --   "gender": "female",
  --   "activity_level": "moderate",
  --   "goal": "weight_loss",
  --   "weight_loss_rate_kg_week": 0.5,
  --   "target_calories": 1800,
  --   "target_protein_g": 158,
  --   "target_carbs_g": 68,
  --   "target_fats_g": 100
  -- }

  -- Dane posiłku (dla meal_eaten)
  meal_data jsonb
  -- Struktura: {
  --   "planned_meal_id": 123,
  --   "recipe_id": 45,
  --   "recipe_name": "Jajecznica z awokado",
  --   "meal_type": "breakfast",
  --   "calories": 350,
  --   "protein_g": 18,
  --   "carbs_g": 8,
  --   "fats_g": 28,
  --   "ingredient_overrides": [...]
  -- }
);

-- 3. Komentarze dla dokumentacji
comment on table public.user_history is 'Historia aktywności użytkownika - profile, posiłki zjedzeniowe';
comment on column public.user_history.event_type is 'Typ zdarzenia: profile_created, profile_updated, meal_eaten';
comment on column public.user_history.event_date is 'Data zdarzenia (bez godziny) dla łatwego grupowania';
comment on column public.user_history.profile_snapshot is 'Snapshot danych profilu w momencie zdarzenia (profile_created/profile_updated)';
comment on column public.user_history.meal_data is 'Dane zjedzonego posiłku z kaloriami i makro (meal_eaten)';

-- 4. Indeksy dla wydajności
create index idx_user_history_user_id on public.user_history(user_id);
create index idx_user_history_user_date on public.user_history(user_id, event_date desc);
create index idx_user_history_event_type on public.user_history(user_id, event_type);

-- 5. RLS: użytkownicy widzą tylko swoją historię
alter table public.user_history enable row level security;

create policy "user_history_select_own"
  on public.user_history for select
  to authenticated using (auth.uid() = user_id);

create policy "user_history_insert_own"
  on public.user_history for insert
  to authenticated with check (auth.uid() = user_id);

create policy "user_history_delete_own"
  on public.user_history for delete
  to authenticated using (auth.uid() = user_id);

-- Uwaga: Brak polityki UPDATE - historia jest niezmienna (tylko dodawanie i usuwanie)
